name: Create Release

on:
  workflow_dispatch:
  push:
    paths:
      - 'wildcards/**'

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setting up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Increment version
        id: increment_version
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          NEW_VERSION=$(npm version patch -m "Bump version to %s")
          echo "new_version=${NEW_VERSION}" >> $GITHUB_OUTPUT

      - name: Create Archive
        run: |
          REPO_NAME=$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}')
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          ZIP_NAME="${REPO_NAME}-${BRANCH_NAME}.zip"
          zip -rj "$ZIP_NAME" wildcards
          echo "zip_name=$ZIP_NAME" >> $GITHUB_OUTPUT
        id: create_zip

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.create_zip.outputs.zip_name }}
          tag_name: ${{ steps.increment_version.outputs.new_version }}

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
          force: true
          tags: true
