name: Update DOWNLOAD.md

on:
  push:
    paths:
      - 'wildcards/**'

jobs:
  update-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update DOWNLOAD.md
        run: |
          ./update-file-list-in-download-md.sh

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add DOWNLOAD.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Update download links"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
