name: Update DOWNLOAD.md

on:
  push:
    paths:
      - 'wildcards/**'

jobs:
  update-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update DOWNLOAD.md
        run: |
          awk '/### Download individual files/{flag=1; print; print ""; next} /^#/{flag=0} flag' DOWNLOAD.md > temp.md
          for file in wildcards/*.txt; do
            filename=$(basename "$file")
            echo "- [$filename](https://github.com/${{ github.repository }}/raw/main/wildcards/$filename)" >> temp.md
          done
          mv temp.md DOWNLOAD.md

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add DOWNLOAD.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Update download links"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
