name: update docs

# on manual run
on:
  workflow_dispatch:

jobs:
  my-job:
    name: update-docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.21

      # run any `bun` or `bunx` command
      # - run: bun install
      - run: bun ./scripts/update-docs.ts
