name: Update Docs

on:
  workflow_dispatch:
  push:
    paths:
      - 'docs/**'
      - 'images/**'
      - 'scripts/**'
      - 'src/**'
      - 'wildcards/**'

jobs:
  update-docs:
    name: Update Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install dependencies
        run: deno install

      - name: Update docs
        run: deno run build

      - name: Commit changes
        run: |
          git config --local user.email "${{ secrets.DYGNITORZ_EMAIL }}"
          git config --local user.name "${{ secrets.DYGNITORZ_NAME }}"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Updated Files"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.DYGNITORZ_TOKEN }}
          branch: ${{ github.ref_name }}
